### ISSUE TITLE
credit the video texts authors

### ISSUE THREAD

**Issue by kartsims** [OMGnetwork/guide#2]
The texts related to the videos should be credited, here's how to do so :

1. Add the contributor's avatar, name and "one-liner" to `contributors.js` (in the root of the repo)
2. Insert the following where the credits are due (replacing the name obviously) :

```
<Contributor name="kartsims"/>
```

The "videos" page source is at `resources/videos.md`.

**Comment by Ro5s** [comment]
Slight additions there: 
https://github.com/OMGnetwork/guide/pull/15
https://github.com/OMGnetwork/guide/pull/16

**Comment by kartsims** [comment]
Nice, thanks ! I think this would be enough to get started, we'll update the rest along the way 👍
