### ISSUE TITLE
Contribute page

### ISSUE THREAD

**Issue by kartsims** [OMGnetwork/guide#3]
The contribute page is actually a copy/paste from another repo. This page should include :

- guidelines to contribute
- a little "how-to" for contributors to spin up the guide in local (install nodejs, etc.)
- the list of contributors

It may be moved to a single page since there might not be enough content to split it across several pages.

**Comment by Ro5s** [comment]
Ok, got a start there: https://github.com/OMGnetwork/guide/pull/14

**Comment by kartsims** [comment]
New proposal #17

**Comment by Ro5s** [comment]
Merged 👍; closing this issue
