### ISSUE TITLE
Benefits : sections removed

### ISSUE THREAD

**Issue by kartsims** [OMGnetwork/guide#4]
The original ["benefits" page](https://kb.buildomg.org/contents/deep-dive/benefits-of-the-omg-network) from the "deep dive" included 5 sections.

Two of these sections were taken from [another page](https://kb.buildomg.org/contents/omg-network-official-guide/how-does-omg-provide-security-scalability-adoption) from the "official guide".

Let's discuss how/if they could be written

**Comment by Ro5s** [comment]
Those 5 sections and title 'Benefits of OMG Network' appear to come from website homepage: https://omisego.network/ 

So, in current 'benefits.md' we have the website's title 'Benefits of....' kinda confusingly mixed with the Official Guide's longer statements on 'Security' and 'Scalability' - - I found the missing reference to 'Mainstream adoption' at bottom of guide/docs/network/adoption.md.

For now, I will revise benefits.md to simply include the missing 'Mainstream adoption' reference from Guide. Let me know if you think we should add the websites' short statements on "Interoperability" and "Decentralized" - - not sure if we are including anything else from website.

**Comment by Ro5s** [comment]
Deleted separate benefits page; closing this issue - see https://github.com/OMGnetwork/guide/pull/12
