### ISSUE TITLE
Author of the "vision" page's quote

### ISSUE THREAD

**Issue by kartsims** [OMGnetwork/guide#5]
There is a nice quote in the beginning of the ["Vision" page](https://omgnetwork.org/guide/vision.html). Its author should be named for clarity purpose.

**Comment by kartsims** [comment]
@nebali  could you help on this one ?

**Comment by Ro5s** [comment]
This PR is the only source I've found so far: https://unitimes.media/auther/12279/

Phrased slightly differently here: https://www.omise.co/omise-funding-led-by-globalbrain

So, might just be credited to OmiseGO?

**Comment by nebali** [comment]
I'm looking for the source, but let's just go with OmiseGO for now. I don't know if we'll be able to track down any one person that wrote it.

**Comment by Ro5s** [comment]
Revised to credit OmiseGO team; see: https://github.com/OMGnetwork/guide/blob/master/docs/vision.md; closing this issue 👍
