### ISSUE TITLE
List partnerships

### ISSUE THREAD

**Issue by kartsims** [OMGnetwork/guide#6]
In the "Business Development" page, it would make sense to list all "official" partnerships (the ones that have been publicly declared).

If it makes sense, maybe we could also publish the rumors.

In both cases, it is very important to quote sources. File to edit : `community/business-development.md`

**Comment by kartsims** [comment]
Here are the two main ones that I know of :

**Hoard**
Hoard Exchange will be a marketplace whereby users can freely buy, rent, sell or trade gaming assets.
Source : https://blog.hoard.exchange/omisego-hoard-creating-a-truly-seamless-game-marketplace-bdebe1b2d272

**Status**
Status intends to bring the benefits of Ethereum on smartphones.
Source : https://blog.status.im/status-partners-with-omisego-565577d2f72

**Comment by Ro5s** [comment]
Made some additions there: https://github.com/OMGnetwork/guide/pull/8

**Comment by kartsims** [comment]
Thanks @Ro5s ! Love the way you sorted them by "category" 💯 

PR is merged, I just changed the plain URLs to links, see syntax :

```markdown
[link text](http://url.com)
```

[Github's guide](https://guides.github.com/features/mastering-markdown/) gives some good markdown tips. 

I unfortunately broke the `omgnetwork.org` URL (will fix soon), so the updated page can be seen here : [https://omgnetwork.github.io/guide/community/business-development.html](https://omgnetwork.github.io/guide/community/business-development.html)

Some additional thoughts for anyone who wants to update the page again before closing the issue :

- A one-line description of each partner would be nice (even for MOUs and SDK implementers)
- Would it be pertinent to date the source link ?
- Gov of Thailand could be added to "Government Outreach" section

**Comment by kartsims** [comment]
Perfect 💯 Thank you !
