### ISSUE TITLE
Improve the README.md

### ISSUE THREAD

**Issue by kartsims** [OMGnetwork/guide#7]
In order to have an "attractive" [repo homepage](https://github.com/OMGnetwork/guide), the `README.md` file should include some basic information such as : 

- one-line description of the repo
- contribution guidelines (see #3)
- step-by-step tutorial to spin the guide in a local environment (including nodejs install)
- mention the usage of vuepress

**Comment by Ro5s** [comment]
Made some improvements: https://github.com/OMGnetwork/guide/pull/13

**Comment by kartsims** [comment]
Thanks! Merged the PR, will add VuePress mention later so I keep the issue open.

Also it feels like there are too many links to the "contributors" page, isn't it ? I'll remove some of them in my upcoming PR, please let me know then if that's OK

**Comment by Ro5s** [comment]
Yeah, we should probably remove extra links. Sounds good!

**Comment by Ro5s** [comment]
Closing per: https://github.com/OMGnetwork/guide/pull/18
